version: '3.7'
services:
  app:
    container_name: clubeincentivo-api
    build: .
    image: clubeincentivo-api
    command: bash -c "npm run 'start:dev'"
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.ssh/:/root/.ssh
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/clubeincentivo_dev
      - ADM_PASSWD=passwd
      - REDIS_URL=redis://redis:6379
      - CLUBE_INVENTIVO_FIREBASE_API_KEY
      - CLUBE_INVENTIVO_FIREBASE_AUTH_DOMAIN
      - CLUBE_INVENTIVO_FIREBASE_DATABASE_URL
    depends_on:
      - db
      - redis
  db:
    image: postgres:10
    container_name: clubeincentivo-db
    restart: always
    volumes:
      -  db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=clubeincentivo_dev
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data:
