version: '3.1'
services:
  app:
    container_name: clubeincentivo-api
    build: .
    image: clubeincentivo-api
    command: bash -c "npm run 'start:dev'"
    #command: tail -f /dev/null
    volumes:
      - .:/app
      - /app/node_modules
      - ~/.ssh/:/root/.ssh
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/clubeincentivo_dev
    depends_on:
      - db
  db:
    image: postgres:10
    container_name: clubeincentivo-db
    restart: always
    volumes:
      -  db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=clubeincentivo_dev
      - POSTGRES_PASSWORD=postgres

volumes:
  db_data:
